<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>zpl</string>
	</array>
	<key>name</key>
	<string>ZIMPL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(subto)\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.zimpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.statement.constraint.zimpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#forall</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#common</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>do</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.statement.do.zimpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#check</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#do</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#print</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#common</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(def(bool|numb|s(et|trg)))\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.zimpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.statement.function.zimpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#forall</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#common</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(m(ax|in)imize)\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.zimpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.statement.objective.zimpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#forall</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#common</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(param)\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.zimpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.statement.param.zimpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#common</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#read</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#read-options</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(set)\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.zimpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.statement.set.zimpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#common</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#read</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#read-options</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(sos)\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.zimpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.statement.sos.zimpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#priority</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sos-type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#common</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(var)\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.zimpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.statement.var.zimpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#index</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#var-types</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>argm</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>argm(ax|in)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.zimpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(:)</string>
					<key>name</key>
					<string>meta.expression.argm.zimpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#in</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#index</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tuple</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>assignment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>:=</string>
					<key>name</key>
					<string>keyword.operator.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>boolean</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(fals|tru)e</string>
					<key>name</key>
					<string>constant.language.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>check</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>check</string>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#.*</string>
					<key>name</key>
					<string>comment.line.number-sign.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>common</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#forall</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#index</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#std-lib</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tuple</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variant</string>
				</dict>
			</array>
		</dict>
		<key>do</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>do</string>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>else</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>else</string>
					<key>name</key>
					<string>keyword.control.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>forall</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>forall</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.zimpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\b(do)|:)</string>
					<key>endCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.zimpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.expression.forall.zimpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#in</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#index</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tuple</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#with</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>in</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>in</string>
					<key>name</key>
					<string>keyword.control.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>index</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[)\s*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.zimpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*(\])</string>
					<key>name</key>
					<string>entity.index.zimpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>entity.other.attribute-name.zimpl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>constant.numeric.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>print</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>print</string>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>priority</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>priority\s+\d+</string>
					<key>name</key>
					<string>keyword.other.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>read</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>read</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.zimpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>as</string>
					<key>name</key>
					<string>meta.expression.read.zimpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>read-options</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>comment|match|use|skip</string>
					<key>name</key>
					<string>keyword.control.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>sos-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>type(1|2)</string>
					<key>name</key>
					<string>support.type.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>std-lib</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>and|not|(x|)or|</string>
					<key>name</key>
					<string>support.function.boolean.zimpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>vabs</string>
					<key>name</key>
					<string>support.function.extended.zimpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>abs|c(ard|eil)|exp|floor|l(ength|og|n)|m(ax|in|od)|ord|prod|r(andom|ound)|s(gn|qrt|um)</string>
					<key>name</key>
					<string>support.function.numeric.zimpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>cross|in(dexset|ter)|ord|p(owerset|roj)|s(ubsets|ymdiff)|union|without</string>
					<key>name</key>
					<string>support.function.set.zimpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>substr</string>
					<key>name</key>
					<string>support.function.string.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.zimpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.zimpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.zimpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-escape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string-escape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\('|\"|\\|/|b|f|n|r|t|v|0)</string>
					<key>name</key>
					<string>constant.character.escape.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>sum</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>sum</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.zimpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\bdo|:)</string>
					<key>name</key>
					<string>meta.expression.sum.zimpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#in</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#index</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tuple</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#with</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>then</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>then</string>
					<key>name</key>
					<string>keyword.control.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>tuple</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.zimpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(&gt;)</string>
					<key>name</key>
					<string>entity.tuple.zimpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>var-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>binary|integer|real</string>
					<key>name</key>
					<string>storage.type.zimpl</string>
				</dict>
			</array>
		</dict>
		<key>variant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(v|)if</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.zimpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>end</string>
					<key>name</key>
					<string>entity.variant.zimpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#then</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#else</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#common</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>with</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>with</string>
					<key>name</key>
					<string>keyword.control.zimpl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.zimpl</string>
	<key>uuid</key>
	<string>e0f40eeb-6c26-430c-bd04-c3272ad89d60</string>
</dict>
</plist>
